# Use a Python base image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV WORKSPACE=/workspace

RUN apt-get update && apt-get install -y \
    curl \
    git \
    ffmpeg \
    libsm6 \
    libxext6

RUN mkdir -p /workspace $WORKSPACE/ComfyUI $WORKSPACE/logs
#RUN git clone https://github.com/nseinturier/ego-diffusion.git $WORKSPACE/ego-diffusion
RUN git clone https://github.com/comfyanonymous/ComfyUI.git $WORKSPACE/ComfyUI
RUN git clone https://github.com/ltdrdata/ComfyUI-Manager.git $WORKSPACE/ComfyUI/custom_nodes/ComfyUI-Manager

WORKDIR /workspace

# Install requirements
RUN pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir -r $WORKSPACE/ComfyUI/requirements.txt
RUN curl -fL https://code-server.dev/install.sh | sh

EXPOSE 8188 8080

# Create an info.txt file (you can modify this content as needed)
RUN echo "ComfyUI is running. Check the logs for more information." > $WORKSPACE/logs/info.txt

# Copy ego-diffusion files into the image
COPY src/ $WORKSPACE/src/
COPY setup.py project_setup.sh requirements.txt run.sh $WORKSPACE/

RUN bash project_setup.sh

# Copy the start script into the image
COPY start.sh $WORKSPACE/start.sh
RUN chmod +x $WORKSPACE/start.sh

# Set the startup command
CMD ["/bin/bash", "/workspace/start.sh"]